#ifndef CONFIG_H
#define CONFIG_H

#ifndef F_CPU
#define F_CPU 8000000UL
#endif

#define ADC_INPUT_CHANNEL 0U
#define ADC_SAMPLE_RATE_HZ 8000UL
#define ADC_TIMER_PRESCALER 8UL
#define ADC_TIMER_OCR ((F_CPU / ADC_TIMER_PRESCALER / ADC_SAMPLE_RATE_HZ) - 1UL)

/* Reserve enough SRAM headroom for feature extraction and ISR stack usage. */
#define UTTERANCE_MAX_SAMPLES 1408U
#define MIN_UTTERANCE_SAMPLES 512U
#define SPEECH_START_THRESHOLD 10U
#define SPEECH_STOP_THRESHOLD 6U
#define SPEECH_START_CONSECUTIVE_SAMPLES 8U
#define SPEECH_STOP_SILENCE_SAMPLES 240U

#define UART_BAUDRATE 9600UL

#define MODEL_ENABLE_EXTERNAL_EEPROM 0U

#define TWI_SCL_HZ 100000UL
#define EEPROM24C512_I2C_ADDR 0x50U

#define LCD_RS_DDR DDRB
#define LCD_RS_PORT PORTB
#define LCD_RS_PIN PB0

#define LCD_RW_DDR DDRB
#define LCD_RW_PORT PORTB
#define LCD_RW_PIN PB2

#define LCD_EN_DDR DDRB
#define LCD_EN_PORT PORTB
#define LCD_EN_PIN PB1

#define LCD_DATA_DDR DDRD
#define LCD_DATA_PORT PORTD
#define LCD_DATA_PIN PIND
#define LCD_DATA_SHIFT 4U

#define LCD_CLEAR_DISPLAY 0x01U
#define LCD_RETURN_HOME 0x02U
#define LCD_ENTRY_MODE_SET 0x06U
#define LCD_DISPLAY_ON 0x0CU
#define LCD_FUNCTION_SET_4BIT 0x28U
#define LCD_SET_CGRAM_ADDR 0x40U
#define LCD_SET_DDRAM_ADDR 0x80U
#define LCD_ROW0_ADDR 0x00U
#define LCD_ROW1_ADDR 0x40U

#endif
